query allPostsQuery {
  ...LayoutQueryFragment
  postConnection(sort: "date" first: 10000) {
    edges {
      node {
        id
        _body
        title
        heroImg
        categories
        date
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}

query blogPostCardQuery($relativePath: String!) {
  post(relativePath: $relativePath) {
    title
    categories
    heroImg
    _body
    date
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}


query categoryQuery($relativePath: String!) {
  ...LayoutQueryFragment
  category(relativePath: $relativePath) {
    ...CategoryParts
  }
  postConnection(sort: "date" first: 10000)
  {
    edges {
      node {
        id
        _body
        title
        heroImg
        categories
        date
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

